import type { ReferenceSchema } from './types';

export const REFERENCE_REGISTRY: Record<string, ReferenceSchema> = {
  currencies: {
    slug: 'currencies',
    name: 'Валюты',
    pluralName: 'Валюты',
    nameSingular: 'валюту',
    category: 'financial',
    model: 'currency',
    scope: 'organization',
    auditable: true,
    description: 'Валюты и денежные единицы (ISO 4217)',
    icon: 'DollarSign',
    fields: [
      { key: 'name',        label: 'Наименование',         type: 'string',  required: true,  width: 180 },
      { key: 'shortName',   label: 'Буквенный код',        type: 'string',  required: true,  width: 100 },
      { key: 'shortSymbol', label: 'Символ',               type: 'string',  required: true,  width: 80  },
      { key: 'code',        label: 'ISO 4217 (буквенный)', type: 'string',  required: true,  width: 120 },
      { key: 'numericCode', label: 'ISO 4217 (цифровой)',  type: 'string',  required: false, width: 120 },
      { key: 'fullName',    label: 'Полное наименование',  type: 'string',  required: false, width: 220 },
      { key: 'englishName', label: 'Наименование (англ.)', type: 'string',  required: false, width: 200, hiddenByDefault: true },
      { key: 'caseForm',    label: 'Форма склонения',      type: 'string',  required: false, width: 180, hiddenByDefault: true },
      { key: 'isSystem',    label: 'Системная',            type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
    ],
  },

  budgetTypes: {
    slug: 'budgetTypes',
    name: 'Типы бюджета',
    pluralName: 'Типы бюджета',
    nameSingular: 'тип бюджета',
    category: 'financial',
    model: 'budgetType',
    scope: 'organization',
    auditable: true,
    description: 'Типы источников финансирования',
    icon: 'Wallet',
    fields: [
      { key: 'name',     label: 'Наименование', type: 'string',  required: true,  width: 240 },
      { key: 'code',     label: 'Код',          type: 'string',  required: true,  width: 140 },
      { key: 'color',    label: 'Цвет',         type: 'color',   required: false, width: 100 },
      { key: 'order',    label: 'Порядок',      type: 'number',  required: false, width: 100, hiddenByDefault: true },
      { key: 'isSystem', label: 'Системный',    type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
    ],
  },

  measurementUnits: {
    slug: 'measurementUnits',
    name: 'Единицы измерения',
    pluralName: 'Единицы измерения',
    nameSingular: 'единицу измерения',
    category: 'common',
    model: 'measurementUnitRef',
    scope: 'organization',
    auditable: true,
    description: 'Единицы измерения по ГОСТ 8.417-2002',
    icon: 'Ruler',
    fields: [
      { key: 'name',      label: 'Наименование',      type: 'string',  required: true,  width: 200 },
      { key: 'shortName', label: 'Обозначение',       type: 'string',  required: true,  width: 120 },
      { key: 'category',  label: 'Категория',         type: 'string',  required: false, width: 160 },
      { key: 'ruCode',    label: 'Код ОКЕИ',          type: 'string',  required: false, width: 100 },
      { key: 'intCode',   label: 'Международный код', type: 'string',  required: false, width: 140, hiddenByDefault: true },
      { key: 'isSystem',  label: 'Системная',         type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
    ],
  },

  declensionCases: {
    slug: 'declensionCases',
    name: 'Падежи',
    pluralName: 'Падежи',
    nameSingular: 'падеж',
    category: 'common',
    model: 'declensionCase',
    scope: 'system',
    adminOnly: true,
    auditable: true,
    description: 'Падежи русского языка для склонения',
    icon: 'Languages',
    fields: [
      { key: 'name',      label: 'Наименование', type: 'string',  required: true,  width: 180 },
      { key: 'shortName', label: 'Краткое',      type: 'string',  required: true,  width: 100 },
      { key: 'order',     label: 'Порядок',      type: 'number',  required: false, width: 100 },
      { key: 'isSystem',  label: 'Системный',    type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
    ],
  },

  // ── REF.4 ──────────────────────────────────────────────────────

  contractKinds: {
    slug: 'contractKinds',
    name: 'Виды контрактов',
    pluralName: 'Виды контрактов',
    nameSingular: 'вид контракта',
    category: 'documentary',
    model: 'contractKind',
    scope: 'organization',
    auditable: true,
    description: 'Виды договоров и контрактов',
    icon: 'Handshake',
    fields: [
      { key: 'name',      label: 'Наименование',         type: 'string',  required: true,  width: 320 },
      { key: 'code',      label: 'Код',                  type: 'string',  required: true,  width: 140 },
      { key: 'shortName', label: 'Краткое наименование', type: 'string',  required: false, width: 120 },
      { key: 'isActive',  label: 'Активный',             type: 'boolean', required: false, width: 100 },
      { key: 'order',     label: 'Порядок',              type: 'number',  required: false, width: 100, hiddenByDefault: true },
      { key: 'isSystem',  label: 'Системный',            type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
    ],
  },

  documentTypes: {
    slug: 'documentTypes',
    name: 'Типы документов',
    pluralName: 'Типы документов',
    nameSingular: 'тип документа',
    category: 'documentary',
    model: 'documentTypeRef',
    scope: 'organization',
    auditable: true,
    description: 'Типы документов ИД и СЭД-модулей',
    icon: 'FileType2',
    fields: [
      { key: 'name',     label: 'Наименование', type: 'string',  required: true,  width: 280 },
      { key: 'code',     label: 'Код',          type: 'string',  required: true,  width: 160 },
      { key: 'module',   label: 'Модуль',       type: 'string',  required: false, width: 120 },
      { key: 'order',    label: 'Порядок',      type: 'number',  required: false, width: 100, hiddenByDefault: true },
      { key: 'isSystem', label: 'Системный',    type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
    ],
  },

  budgetExpenseItems: {
    slug: 'budgetExpenseItems',
    name: 'Статьи расходов',
    pluralName: 'Статьи расходов',
    nameSingular: 'статью расходов',
    category: 'financial',
    model: 'budgetExpenseItem',
    scope: 'organization',
    auditable: true,
    hierarchical: true,
    parentKey: 'parentId',
    description: 'Иерархия статей расходов',
    icon: 'Receipt',
    fields: [
      { key: 'name',     label: 'Наименование', type: 'string',  required: true,  width: 280 },
      { key: 'code',     label: 'Код',          type: 'string',  required: true,  width: 120 },
      { key: 'isActive', label: 'Активный',     type: 'boolean', required: false, width: 100 },
      { key: 'order',    label: 'Порядок',      type: 'number',  required: false, width: 100, hiddenByDefault: true },
      { key: 'isSystem', label: 'Системный',    type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
      // Не рендерятся в таблице/форме, но принимаются API при создании дочерних записей
      { key: 'parentId', label: 'Родитель',     type: 'string',  required: false, hidden: true },
      { key: 'level',    label: 'Уровень',      type: 'number',  required: false, hidden: true },
    ],
  },

  // ── REF.5 ──────────────────────────────────────────────────────

  taskTypeRefs: {
    slug: 'taskTypeRefs',
    name: 'Типы задач',
    pluralName: 'Типы задач',
    nameSingular: 'тип задачи',
    category: 'common',
    model: 'taskTypeRef',
    scope: 'organization',
    auditable: true,
    description: 'Типы задач планировщика',
    icon: 'CheckSquare',
    fields: [
      { key: 'name',     label: 'Наименование', type: 'string',  required: true,  width: 200 },
      { key: 'code',     label: 'Код',          type: 'string',  required: true,  width: 140 },
      { key: 'color',    label: 'Цвет',         type: 'color',   required: false, width: 100 },
      { key: 'icon',     label: 'Иконка',       type: 'string',  required: false, width: 120 },
      { key: 'order',    label: 'Порядок',      type: 'number',  required: false, width: 100, hiddenByDefault: true },
      { key: 'isActive', label: 'Активный',     type: 'boolean', required: false, width: 100 },
      { key: 'isSystem', label: 'Системный',    type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
    ],
  },

  defectCategories: {
    slug: 'defectCategories',
    name: 'Категории недостатков',
    pluralName: 'Категории недостатков',
    nameSingular: 'категорию недостатков',
    category: 'construction',
    model: 'defectCategoryRef',
    scope: 'organization',
    auditable: true,
    description: 'Категории строительных недостатков',
    icon: 'AlertTriangle',
    fields: [
      { key: 'name',               label: 'Наименование',         type: 'string',  required: true,  width: 280 },
      { key: 'code',               label: 'Код',                  type: 'string',  required: true,  width: 160 },
      { key: 'color',              label: 'Цвет',                 type: 'color',   required: false, width: 100 },
      { key: 'requiresSuspension', label: 'Требует приостановки', type: 'boolean', required: false, width: 160 },
      { key: 'order',              label: 'Порядок',              type: 'number',  required: false, width: 100, hiddenByDefault: true },
      { key: 'isActive',           label: 'Активный',             type: 'boolean', required: false, width: 100 },
      { key: 'isSystem',           label: 'Системный',            type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
    ],
  },

  problemIssueTypes: {
    slug: 'problemIssueTypes',
    name: 'Типы проблемных вопросов',
    pluralName: 'Типы проблемных вопросов',
    nameSingular: 'тип проблемного вопроса',
    category: 'construction',
    model: 'problemIssueTypeRef',
    scope: 'organization',
    auditable: true,
    description: 'Типы проблемных вопросов',
    icon: 'HelpCircle',
    fields: [
      { key: 'name',     label: 'Наименование', type: 'string',  required: true,  width: 280 },
      { key: 'code',     label: 'Код',          type: 'string',  required: true,  width: 200 },
      { key: 'order',    label: 'Порядок',      type: 'number',  required: false, width: 100, hiddenByDefault: true },
      { key: 'isActive', label: 'Активный',     type: 'boolean', required: false, width: 100 },
      { key: 'isSystem', label: 'Системный',    type: 'boolean', required: false, readonly: true, hiddenByDefault: true },
    ],
  },

  // ── REF.7 — интеграция существующих моделей ──────────────────────

  ksi: {
    slug: 'ksi',
    name: 'КСИ',
    pluralName: 'КСИ',
    nameSingular: 'узел КСИ',
    category: 'construction',
    model: 'ksiNode',
    scope: 'system',
    auditable: true,
    hierarchical: true,
    lazyLoad: true,
    parentKey: 'parentId',
    icon: 'FolderTree',
    description: 'Классификатор строительной информации по ОКС Минстроя РФ',
    fields: [
      { key: 'code',        label: 'Код',          type: 'string',   required: true,  width: 140 },
      { key: 'name',        label: 'Наименование',  type: 'string',   required: true,  width: 320 },
      { key: 'description', label: 'Описание',      type: 'textarea', required: false },
      { key: 'tableCode',   label: 'Таблица',       type: 'string',   required: false, width: 120 },
      { key: 'level',       label: 'Уровень',       type: 'number',   required: false, width: 90, readonly: true },
      { key: 'parentId',    label: 'Родитель',      type: 'string',   required: false, hidden: true },
    ],
  },

  nomenclature: {
    slug: 'nomenclature',
    name: 'Номенклатура материалов',
    pluralName: 'Номенклатура материалов',
    nameSingular: 'позицию номенклатуры',
    category: 'construction',
    model: 'materialNomenclature',
    scope: 'organization',
    auditable: true,
    icon: 'Package',
    description: 'Справочник номенклатуры материалов организации',
    fields: [
      { key: 'name',       label: 'Наименование', type: 'string', required: true,  width: 280 },
      { key: 'unit',       label: 'Ед. изм.',     type: 'string', required: false, width: 100 },
      { key: 'category',   label: 'Категория',    type: 'string', required: false, width: 160 },
      { key: 'vendorCode', label: 'Артикул',      type: 'string', required: false, width: 140 },
    ],
  },

  stampTitles: {
    slug: 'stamp-titles',
    name: 'Заголовки штампов',
    pluralName: 'Заголовки штампов',
    nameSingular: 'заголовок штампа',
    category: 'documentary',
    model: 'stampTitle',
    scope: 'organization',
    auditable: true,
    icon: 'Stamp',
    description: 'Справочник заголовков для штампов PDF-документов',
    fields: [
      { key: 'name',     label: 'Наименование',       type: 'string',   required: true,  width: 280 },
      { key: 'template', label: 'Handlebars-шаблон',  type: 'textarea', required: false },
    ],
  },

  documentTemplates: {
    slug: 'document-templates',
    name: 'Шаблоны документов',
    pluralName: 'Шаблоны документов',
    nameSingular: 'шаблон документа',
    category: 'documentary',
    model: 'documentTemplate',
    scope: 'organization',
    auditable: true,
    icon: 'FileText',
    description: 'Шаблоны документов (.docx с плейсхолдерами)',
    fields: [
      { key: 'name',     label: 'Название',    type: 'string',  required: true,  width: 280 },
      {
        key: 'category', label: 'Категория',   type: 'select',  required: true,  width: 180,
        options: [
          { value: 'AOSR',           label: 'АОСР (скрытые работы)' },
          { value: 'OZR',            label: 'ОЖР' },
          { value: 'KS2',            label: 'КС-2' },
          { value: 'KS3',            label: 'КС-3' },
          { value: 'AVK',            label: 'АВК (входной контроль)' },
          { value: 'ZHVK',           label: 'ЖВК (журнал ВК)' },
          { value: 'TECH_READINESS', label: 'Акт технической готовности' },
          { value: 'OTHER',          label: 'Прочие' },
        ],
      },
      { key: 'version',  label: 'Версия',      type: 'string',  required: false, width: 100 },
      { key: 'isActive', label: 'Активный',    type: 'boolean', required: false, width: 100 },
      { key: 'isPublic', label: 'Публичный',   type: 'boolean', required: false, width: 100 },
    ],
  },

  taskTypes: {
    slug: 'task-types',
    name: 'Типы задач',
    pluralName: 'Типы задач',
    nameSingular: 'тип задачи',
    category: 'common',
    model: 'taskType',
    scope: 'organization',
    auditable: true,
    defaultSort: 'name',
    icon: 'Tag',
    description: 'Справочник типов задач планировщика',
    fields: [
      { key: 'name',     label: 'Наименование', type: 'string',  required: true,  width: 240 },
      { key: 'key',      label: 'Ключ',         type: 'string',  required: true,  width: 140 },
      { key: 'isSystem', label: 'Системный',    type: 'boolean', required: false, width: 100, readonly: true },
    ],
  },
};

export function getReferenceSchema(slug: string): ReferenceSchema | null {
  return REFERENCE_REGISTRY[slug] ?? null;
}

export function listReferenceSchemas(): ReferenceSchema[] {
  return Object.values(REFERENCE_REGISTRY);
}
