-- AlterEnum: SpecialJournalType — добавление 20 типов журналов ЦУС (2026-04-14)
-- PostgreSQL ADD VALUE не поддерживает транзакции напрямую, поэтому каждое значение добавляется отдельно.

ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'OZR_1026PR';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'OZR_RD_11_05';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'INPUT_CONTROL';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'CONSTRUCTION_CONTROL';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'CONSTRUCTION_CONTROL_V2';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'SK_CALL_REGISTER';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'AUTHOR_SUPERVISION_2016';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'DRILLING_WORKS';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'CONCRETE_CURING';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'JOINT_GROUTING';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'ANTICORROSION_WELD';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'BOLT_CONNECTIONS';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'TORQUE_WRENCH_CALIBRATION';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'CABLE_TUBE';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'CABLE_ROUTE';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'PIPELINE_WELDING';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'INSULATION_LAYING';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'TECHNICAL_LEVELING';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'FIRE_SAFETY_INTRO';
ALTER TYPE "SpecialJournalType" ADD VALUE IF NOT EXISTS 'GENERAL_INTRO_BRIEFING';
