/**
 * Декларативная матрица прав: WorkspaceRole → набор разрешённых Action.
 * Если действие не указано — запрещено (deny-by-default).
 *
 * ВНИМАНИЕ: Изменение этого файла влияет на всю систему прав.
 * После изменений — обновить unit-тесты в src/lib/__tests__/permissions.test.ts.
 */
import { WorkspaceRole } from '@prisma/client';
import { ACTIONS, Action } from './actions';

export const PERMISSION_MATRIX: Record<WorkspaceRole, Action[]> = {
  // OWNER — всё
  OWNER: Object.values(ACTIONS) as Action[],

  ADMIN: [
    ACTIONS.WORKSPACE_MANAGE_MEMBERS,
    ACTIONS.WORKSPACE_EDIT_PROFILE,
    ACTIONS.WORKSPACE_INVITE_GUEST,
    ACTIONS.PROJECT_CREATE,
    ACTIONS.PROJECT_VIEW,
    ACTIONS.PROJECT_EDIT,
    ACTIONS.PROJECT_DELETE,
    ACTIONS.PROJECT_PUBLISH_DASHBOARD,
    ACTIONS.PROJECT_MANAGE_MEMBERS,
    ACTIONS.DOCUMENT_CREATE,
    ACTIONS.DOCUMENT_EDIT,
    ACTIONS.DOCUMENT_DELETE,
    ACTIONS.DOCUMENT_SIGN,
    ACTIONS.DOCUMENT_VIEW_COSTS,
    ACTIONS.ESTIMATE_CREATE,
    ACTIONS.ESTIMATE_EDIT,
    ACTIONS.ESTIMATE_VIEW_PRICES,
    ACTIONS.PHOTO_UPLOAD,
    ACTIONS.PHOTO_DELETE,
    ACTIONS.PHOTO_VIEW_PRIVATE,
    ACTIONS.COMMENT_CREATE,
    ACTIONS.COMMENT_RESOLVE,
    ACTIONS.MARKETPLACE_CREATE_LISTING,
    ACTIONS.MARKETPLACE_RESPOND,
  ],

  MANAGER: [
    ACTIONS.PROJECT_VIEW,
    ACTIONS.PROJECT_EDIT,
    ACTIONS.PROJECT_MANAGE_MEMBERS,
    ACTIONS.DOCUMENT_CREATE,
    ACTIONS.DOCUMENT_EDIT,
    ACTIONS.DOCUMENT_SIGN,
    ACTIONS.DOCUMENT_VIEW_COSTS,
    ACTIONS.ESTIMATE_CREATE,
    ACTIONS.ESTIMATE_EDIT,
    ACTIONS.ESTIMATE_VIEW_PRICES,
    ACTIONS.PHOTO_UPLOAD,
    ACTIONS.PHOTO_VIEW_PRIVATE,
    ACTIONS.COMMENT_CREATE,
    ACTIONS.COMMENT_RESOLVE,
  ],

  ENGINEER: [
    ACTIONS.PROJECT_VIEW,
    ACTIONS.DOCUMENT_CREATE,
    ACTIONS.DOCUMENT_EDIT,
    ACTIONS.DOCUMENT_SIGN,
    ACTIONS.ESTIMATE_CREATE,
    ACTIONS.ESTIMATE_EDIT,
    ACTIONS.ESTIMATE_VIEW_PRICES,
    ACTIONS.PHOTO_UPLOAD,
    ACTIONS.PHOTO_VIEW_PRIVATE,
    ACTIONS.COMMENT_CREATE,
  ],

  FOREMAN: [
    ACTIONS.PROJECT_VIEW,
    ACTIONS.DOCUMENT_CREATE,
    ACTIONS.DOCUMENT_EDIT,
    ACTIONS.PHOTO_UPLOAD,
    ACTIONS.COMMENT_CREATE,
    ACTIONS.COMMENT_RESOLVE,
  ],

  WORKER: [
    ACTIONS.PROJECT_VIEW,
    ACTIONS.PHOTO_UPLOAD,
    ACTIONS.COMMENT_CREATE,
  ],

  // MEMBER — устаревшая роль, сохранена для обратной совместимости.
  // Права как у WORKER — минимальный доступ только на чтение и загрузку фото.
  MEMBER: [
    ACTIONS.PROJECT_VIEW,
    ACTIONS.PHOTO_UPLOAD,
    ACTIONS.COMMENT_CREATE,
  ],

  GUEST: [
    ACTIONS.PROJECT_VIEW,
    ACTIONS.COMMENT_CREATE,
    // DOCUMENT_SIGN добавляется через guestScope.permissions.canSignActs
    // DOCUMENT_VIEW_COSTS добавляется через guestScope.permissions.canViewCosts
  ],

  CUSTOMER: [
    ACTIONS.PROJECT_VIEW,
    ACTIONS.PROJECT_CREATE,   // может создать свой объект (MODULE17 — Мой Ремонт)
    ACTIONS.PROJECT_EDIT,     // только свои объекты
    ACTIONS.DOCUMENT_VIEW_COSTS,
    ACTIONS.PHOTO_UPLOAD,
    ACTIONS.COMMENT_CREATE,
  ],
};
